# Config for CRW model.

_target_: video_cv_project.models.CRW
encoder:
  _target_: video_cv_project.models.encoders.create_resnet_encoder
  name: resnet18
  del_layers:
    - layer4
edge_dropout: 0.1
feat_dropout: 0.1
temperature: 0.07
head_depth: 1
num_feats: 128
