# Config for CRW model.

_target_: video_cv_project.models.CRW
encoder:
  _target_: video_cv_project.models.encoders.EncoderWithGRU
  # TODO: How to load CRW pretrained models here?
  encoder:
    _target_: video_cv_project.models.encoders.create_resnet_encoder
    name: resnet18
    weights: null
    # del_layers: [layer4]
  hid_dim: 256
  size: 3
  depth: 1
  device: ${..device}
patch_transform:
  - _target_: video_cv_project.data.transforms.MapTransform
  - _target_: video_cv_project.data.transforms.PatchSplitJitterTransform
    size: 64
    stride: 32
    scale: [0.7, 0.9]
    ratio: [0.8, 1.2]
edge_dropout: 0.0
feat_dropout: 0.0
temperature: 0.05
head_depth: 1
num_feats: 128
device: ${device}
