# Config for SlotCPC model.

time_steps: 5
num_slots: 7
num_iters: 2
_target_: video_cv_project.models.SlotCPC
model:
  _target_: video_cv_project.models.SlotModel
  slot_dim: 512
  slot_hid_dim: 512
  slot_predict_heads: 4
  encoder:
    _target_: transformers.ViTModel.from_pretrained
    pretrained_model_name_or_path: facebook/dino-vits16
    add_pooling_layer: false
decoder:
  _target_: video_cv_project.models.heads.AlphaSlotDecoder
  slot_dim: 512
  # TODO: This is auto-detectable, just no nice way to pass to decoder init.
  size: [384, 14, 14]
  depth: 4
  hid_dim: 384
