# Config replicating DINOSAUR.

_target_: dinosavi.models.DINOSAUR
num_slots: 10
num_iters: 3

model:
  _target_: dinosavi.models.SlotModel
  slot_dim: 256
  slot_hid_dim: 1024
  use_bgfg_groups: false
  enc_cfg:
    _target_: transformers.ViTConfig.from_pretrained
    pretrained_model_name_or_path: ${vit_path}
  # Using None below disables slot propagation altogether.
  slot_predictor: null

decoder:
  _target_: dinosavi.models.heads.AlphaSlotDecoder
  slot_dim: ${..model.slot_dim}
  # Should match dims of model.encoder's output feature map.
  out_dim: ${hparam.general.out_dim}
  depth: 4
  kernel_size: 1
  hid_dim: 1024
  pe_type: learnt
  # Decoder handles positional encoding interpolation.
  pe_size: ${hparam.decode.pe_size}
