# @package _global_
# Config for cache mode.

defaults:
  - slot-base
  - override /data: kinetics400
  - override /data/transform: base
  - override /model: none

mode: cache

model:
  _target_: video_cv_project.data.transform.PatchAndViT
  name: ${vit_path}
  # 512 + 256 + 128. Highest "nice" batch size for 48GB of VRAM.
  batch_size: 896
  compile: true
  cache_dir: /home/jovyan/workspaces/video-cv-project/artifacts/cache

train:
  epochs: 1
  log_every: 20
  save_every: -1

sampler:
  _target_: torchvision.datasets.samplers.UniformClipSampler
  # Kinetics400 videos are ~10s each. At 8 fps, each video has ~80 frames.
  num_clips_per_video: 80

data:
  cache_path: /home/jovyan/downloads/kinetics400-train.pt
  batch_size: ${..model.batch_size}
  num_workers: 32
  dataset:
    # Ensure every frame is cached.
    frames_per_clip: 1
    step_between_clips: 1
    split: train

  transform:
    patch_func: null

  # Workaround for config merge.
  sampler: ${sampler}
