# @package _global_
# Config for eval mode for SlotModel.

defaults:
  - slot-base
  # Model config loaded from checkpoint.
  - override /model: none
  - override /data: davis

mode: eval-slot

# If None, will be detected from model.
num_slots:
num_iters:
ini_iters:

# Output to use:
# - slot: Slot Attention weights.
# - alpha: Alpha mask from Decoder.
output: slot # alpha

# Whether to use lock-on.
lock_on: true
# [Lock on only] Slots per class.
slots_per_class: 1
# [Lock on only] Number of slots to use for background.
num_bg_slots: 8

data:
  dataset:
    context_len: 0

  transform:
    im_transforms:
      - _target_: video_cv_project.data.transform.HFTransform
        name: ${vit_path}
        do_resize: false
        size:
          height: 360
          width: 480

    patch_func:
      compile: false
      batch_size: 4
      device: cuda
