# @package _global_
# Config for eval mode for SlotModel.

defaults:
  - slot-base
  - override /model: slot
  - override /data: davis

mode: eval-slot

data:
  dataset:
    context_len: 0

  transform:
    im_transforms:
      - _target_: video_cv_project.data.transform.HFTransform
        name: ${vit_path}
        do_resize: false
        size:
          height: 360
          width: 480

    patch_func:
      # ViT encoding done on GPU during eval, can use higher batch size.
      # Unless `do_resize` above is false.
      batch_size: 1
