# @package _global_
# Config for train mode.

defaults:
  - override /data: kinetics400

mode: train

train:
  epochs: 3

  log_every: 20

  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003

  scheduler:
    _target_: torch.optim.lr_scheduler.MultiStepLR
    milestones: [0.7, 0.8, 0.9]
    gamma: 0.5

model:
  edge_dropout: 0.1
  feat_dropout: 0.05
  temperature: 0.05
