# @package _global_
# Config for train mode.

defaults:
  - /transform: train
  - /model: crw

mode: train

epochs: 5

model:
  edge_dropout: 0.1
  feat_dropout: 0.1
  temperature: 0.07

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  milestones: [4, 5]
  gamma: 0.1
