# @package _global_
# Config for train mode.

defaults:
  - override /data: kinetics400

mode: train

train:
  epochs: 3

  log_every: 20

  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0003

  scheduler:
    _target_: torch.optim.lr_scheduler.MultiStepLR
    milestones: [1, 2]
    gamma: 0.1

model:
  edge_dropout: 0.1
  feat_dropout: 0.05
  temperature: 0.05
